[google_service_account]
type = "service_account"
project_id = "avacare-patient-records"
private_key_id = "e058add0004825c850750f81146acc17ec567f3c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASC...
...REMAINDER OF YOUR KEY HERE...
-----END PRIVATE KEY-----"""
client_email = "avacare-service@avacare-patient-records.iam.gserviceaccount.com"
client_id = "103454986058063814595"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/avacare-service%40avacare-patient-records.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
