[gcp_service_account]
type = "service_account"
project_id = "avacare-patient-records"
private_key_id = "e058add0004825c850750f81146acc17ec567f3c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkh5iF8w0qtc4q
rqzhsJSGp6tM7LU4xjolyIQjVUlhIFD4ZoZqexIBx0vAtRsJtCXmMEHA5FcIbdRW
GKFFpM4YaewaZJa4AzGOTheWs89fFXfa52vyz01+MXnxEJn/Fqn4qrOq4h4R+QkK
YCbbjNilwr7UxEFXu9Mhhhz7kxT8UggW6P6DzV6a6uszMNSwMReNH/V/dQ9TWzH0
ipJCikLJA7y0Jw6BYiRq9gDT06lWnTpSfSpPbWHK5Gi3RyC6ZVWcMB7fHvdgQtRt
+tSfQbL0JN/WlzLUqx2PSZHhXdddauHh9nNzsGladFrSmDy4n1SIXTQ0/X6pPv1R
o+p5tjArAgMBAAECggEALfWeupQ5clvU2oFu06Ci7LZ7mIJq4RAmgBVyK/iQBeyk
Ea96DtaQIiUM2Sj+A4jqKVIDnCFs2nLrpJ0+t5ig5Zr5FCpTG9XwiuLvne5emB4E
HAcXVX1pFT425QsRKXuoQUlV5P9DDRw21UoksKG4hx1Od1rXMe3KvYucHv5oF09T
+coBjyPh1uigZiXm+oaECDC2gqQsHKydbdeuQwJP49EsioOnhRp2SelbgDuTlz5h
xqsiDScfuXvKLh2vylkYaxGr4oq9KnIytCaodJv2oxf1/5mHx7AtKzCNOuaRVG1F
iTLipGOubQMxsVwJVWg9Q/aELn9ZZ4b/schIE7MPSQKBgQDb91SK6q4m/r/Ji3jr
Wu0rUssqBkl4Obh0jmBsxb3atFIfjtJlDU8vvw5LqPCZ/aInMvpSAien/RCycW7n
zTyri+DgYg404Uv1JP7G45xIbCymsdplrkt3+N8WYZtYvwAXeg68wEpiZWY7q9ym
8J8aRrSbHF9CFFjnibNch0N83wKBgQC/e3BwSC2Ql2S9dwXa3i/gVPIhPpjOelKu
fGzY6r6T/OgW5Hiyj2mX6YlMPUnXwDV/mBgRs3aER6HLeTVs2PQ28ol1f10y6JQM
EfCJW/3cF5aLrnvXd4H+K1i0B2eY4Vzgmv7qNoT2NYLujNTp9QGokjxgQIxWvzU3
QtfKkRdqNQKBgG2GYVoqMDzKa8R25eaKh70ipHZwWvS6CNZAblK6wyW604lTG/+k
+ODVSNDzdZm3aJ4MDAf5erVylHXFdWuGDcd9BqOzL0+1PpT5rsJpYs/MzQ7TT+OB
PaKnEK2cPDWcJPeLlvr05BTKWHUtxdh5xz7WJed14RiN+RaQwfY4g6oRAoGBAKgG
xOrym3FHOHJ90Fh4IqEDSZncmTCO7KEKtGVA0M2B35O/Fx7xc+KHXyDUo0i89PUr
XOujhLudNCAeE8CZPOw+tlqx0fHLX6ab02xlmgWZeVTHXwr7ZsnH9cW8va7NC7hY
qpqSDukSmfuE/4zxn2vyLyLzYXL5xNPiRwQNf/OFAoGAYzapuoQaXXFPhvPu5aJp
O0LACud6aOJ4qifXEUygif9ra3WZrMAmbpEDaM74Xm6zZ71oVzmSCGNriuUX99eZ
+xKxvduQS6TMJ3o7RQou+byOIEbzvfs6rFZe5yJyEiQJd79oXW/aTPd5WKlCUVng
WaG3DiOnDDOm9nDnPS7Eg5E=
-----END PRIVATE KEY-----"""
client_email = "avacare-service@avacare-patient-records.iam.gserviceaccount.com"
client_id = "103454958068506831455"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/avacare-service%40avacare-patient-records.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[weather_api]
api_key = "cc5ca5e6f0b9ccf2d197b74131bc4397"
